checks:
    php:
      code_rating: true
      duplication: false
build:
    tests:
        override:
            -
                command: 'phpunit --coverage-clover=coverage.clover'
                coverage:
                    file: 'coverage.clover'
                    format: 'clover'
    environment:
        php:
            version: 7.1.0
filter:
    excluded_paths:
        - tests/*
        - docs/*
        - vendor/*
        - example.php
